---
title: "Invasive Species Encounters and Treatments in Vermont"
format: html
---

```{r}
#| label: Initialize project
#| warning: false
#| code-fold: true
library(tidyverse)
library(here)
library(rnaturalearth)
library(sf)
library(RColorBrewer)
library(viridisLite)
```

```{r}
Invasive_Species <- read_csv(here("data", "Invasive_Species.csv"))
# Data source: Vermont Center for Geographic Information (VCGI), https://catalog.data.gov/dataset/invasive-species-812ab
```

## Introduction

This project utilizes data from the Vermont Center for Geographic Information (VCGI). 

As of publishing, the data is hosted at this link:
https://catalog.data.gov/dataset/invasive-species-812ab 

## Understanding invasive species

```{r}
Invasive_Species |>
  ggplot(aes(x = InvasiveName)) +
  geom_bar() +
  coord_flip() +
  labs(x = "Invasive species name", y = "Count")
```

```{r}
TopInvasive <- Invasive_Species |>
  group_by(InvasiveName) |>
  count() |>
  filter(n > 6)

Top_Invasive_Species <- Invasive_Species |>
  inner_join(TopInvasive, by = join_by(InvasiveName)) |>
  mutate(year = str_sub(ObservationDate, -4, str_length(ObservationDate)))
```

```{r}
Top_Invasive_Species |>
  ggplot(aes(x = PlantDescription, fill = InvasiveName)) +
  geom_bar(color = "black") +
  coord_flip() +
  labs(x = "Plant description", y = "Count", fill = "Species")
```

TODO: Explain Hemlock Woolly Adelgid


```{r}
invasive_boundaries <- read_sf(here("data/Invasive_Species_Shapefiles", "Invasive_Species.dbf"))
```

```{r}
# Shapemap of Vermont counties
vt_boundaries <- read_sf(here("data/VT_County_Shapefiles", "FS_VCGI_OPENDATA_Boundary_BNDHASH_poly_counties_SP_v1.dbf"))
```

```{r}
#ADD ALT TEXT
#ADD CAPTION

# Spatial point map of invasive species encounters
invasive_boundaries |>
  mutate(GrossArea = as.numeric(GrossArea)) |>
  inner_join(Top_Invasive_Species) |>
  filter(InvasiveNa == "Hemlock Woolly Adelgid") |>
  ggplot() +
  geom_sf(data = vt_boundaries) +
  geom_sf(aes(color = year),
          size = 3,
          alpha = 0.5) +
  labs(title = "Hemlock Woolly Adelgid sightings in Vermont", color = "Invasive species", y = "Latitude", x = "Longitude") +
  scale_color_viridis_d()
```




