---
title: "SamF_Teamwork"
format: html
---

Title:Overview of the Research on Team Effectiveness

Citation : Committee on the Science of Team Science; Board on Behavioral, Cognitive, and Sensory Sciences; Division of Behavioral and Social Sciences and Education; National Research Council; Cooke NJ, Hilton ML, editors. Enhancing the Effectiveness of Team Science. Washington (DC): National Academies Press (US); 2015 Jul 15. 3, Overview of the Research on Team Effectiveness. Available from: https://www.ncbi.nlm.nih.gov/books/NBK310384/

Summary: This article is interesting in that it's organized like a scientific article. It's cool in that it describes and explains "simple" or "common sense" good teamwork aspects in a more scientific method. While the article focuses on Science research groups but should also apply in general. Main points include mental models, cognitive interactions, team climate and psychological safety. These points boil down to creating a space where people feel safe, respected, heard and free to take risks. The point being that people work best when comfortable. The rest of the article talks about Team Efficacy and how it's effected by Team Cohesion and how to measure Team  Effectiveness. This can be simplified to how teams work better when people do what they're good at, don't argue/ can resolve arguments well and then you can measure group effectiveness on. Mostly it's about how much people get done and how they feel emotionally while getting it done. This article is interesting for focusing on rescearching team effectiveness.
